#===============================================================================
# Wonder Trade
# By Dr.Doom76
#===============================================================================
module WonderTradeSettings
 # This is a list of Blocklisted Pokemon. These Pokemon will be considered for trade.
 # Format is [:POKEMON1, :POKEMON2]
 USE_BLOCKLIST = false
 
 BLOCKLIST_POKEMON = []
 
 # This is a list of Allowlisted Pokemon. These Pokemon will be pushed into the trade pool.
 # The first thing is the species of the Pokemon you want an extra "chance" of getting.
 # The second thing is the number of "chances" you wish to add.
 # The higher the number, the lower the rarity is going to be.
 # Format is as follows:
 #ALLOWLIST_POKEMON = {
 # :MELOETTA => 5,
 # :RATTATA => 10,
 # :PIKACHU => 30
 #  }

 USE_ALLOWLIST = false

 ALLOWLIST_POKEMON = {

}
 
 # Setting for Male and Female names. Names are randomly selected from one of the listed, if not otherwised defined.
 MALE_NAMES = [
    "Adam",
  "Alexander",
  "Anthony",
  "Austin",
  "Benjamin",
  "Blake",
  "Brandon",
  "Brian",
  "Charles",
  "Christopher",
  "Cody",
  "Connor",
  "Daniel",
  "David",
  "Donald",
  "Dylan",
  "Edward",
  "Eric",
  "Ethan",
  "Frank",
  "Gabriel",
  "Gregory",
  "Hunter",
  "Jacob",
  "James",
  "Jason",
  "Jeffrey",
  "Jeremy",
  "Jonathan",
  "Joseph",
  "Joshua",
  "Justin",
  "Kenneth",
  "Kevin",
  "Larry",
  "Logan",
  "Mark",
  "Matthew",
  "Michael",
  "Nathan",
  "Nicholas",
  "Patrick",
  "Paul",
  "Philip",
  "Raymond",
  "Richard",
  "Robert",
  "Samuel",
  "Scott",
  "Sean",
  "Stephen",
  "Steven",
  "Thomas",
  "Terry",
  "Travis",
  "Tyler",
  "William",
  "Zachary",
]

FEMALE_NAMES = [
  "Amanda",
  "Amy",
  "Andrea",
  "Angela",
  "Anna",
  "Ashley",
  "Barbara",
  "Betty",
  "Brenda",
  "Carol",
  "Carolyn",
  "Catherine",
  "Charlotte",
  "Christina",
  "Cynthia",
  "Deborah",
  "Debra",
  "Diane",
  "Donna",
  "Dorothy",
  "Elizabeth",
  "Emily",
  "Emma",
  "Evelyn",
  "Frances",
  "Gloria",
  "Grace",
  "Hannah",
  "Helen",
  "Isabella",
  "Janet",
  "Jasmine",
  "Jessica",
  "Joan",
  "Judy",
  "Julia",
  "Karen",
  "Kathleen",
  "Kimberly",
  "Laura",
  "Lauren",
  "Linda",
  "Lisa",
  "Madison",
  "Margaret",
  "Marie",
  "Martha",
  "Mary",
  "Melissa",
  "Michelle",
  "Nancy",
  "Pamela",
  "Patricia",
  "Rachel",
  "Rebecca",
  "Sandra",
  "Sarah",
  "Sharon",
  "Shirley",
  "Sophia",
  "Stephanie",
  "Teresa",
  "Virginia",
]

# Settings for nick names. If true, it will randomly assign a nickname from the list below, if a nickname is not passed through an argument.
USE_NICKNAME = true

POKEMON_NICKNAMES = [
  "Abyss",
  "Aqua",
  "Ash",
  "Auric",
  "Aurora",
  "Basil",
  "Blaze",
  "Blizzard",
  "Bolt",
  "Boulder",
  "Bramble",
  "Breeze",
  "Breezy",
  "Buddy",
  "Cascade",
  "Canyon",
  "Celeste",
  "Charcoal",
  "Chasm",
  "Cliff",
  "Cobalt",
  "Comet",
  "Crag",
  "Crimson",
  "Crescent",
  "Cypress",
  "Dandelion",
  "Dawn",
  "Drift",
  "Drizzle",
  "Dusty",
  "Dusk",
  "Echo",
  "Ember",
  "Emberly",
  "Emberstorm",
  "Fable",
  "Fang",
  "Flare",
  "Flint",
  "Flicker",
  "Frost",
  "Frostbite",
  "Frosty",
  "Gale",
  "Glider",
  "Glimmer",
  "Glint",
  "Gust",
  "Harbor",
  "Hollow",
  "Inferno",
  "Ivory",
  "Jet",
  "Luna",
  "Lunar",
  "Maple",
  "Marble",
  "Marsh",
  "Meadow",
  "Mocha",
  "Moss",
  "Misty",
  "Mystic",
  "Nimbus",
  "Nova",
  "Obsidian",
  "Onyx",
  "Pebble",
  "Pebbles",
  "Phantom",
  "Phoenix",
  "Pine",
  "Puddle",
  "Quartz",
  "Raindrop",
  "River",
  "Rocky",
  "Rumble",
  "Rustle",
  "Rusty",
  "Saber",
  "Sapphire",
  "Scarlet",
  "Seraph",
  "Shade",
  "Shadow",
  "Shale",
  "Shiver",
  "Skye",
  "Smokey",
  "Solace",
  "Solstice",
  "Soot",
  "Sparky",
  "Sparrow",
  "Specter",
  "Spike",
  "Storm",
  "Stormy",
  "Sundrop",
  "Sunny",
  "Sylph",
  "Tempest",
  "Thistle",
  "Thorn",
  "Thunder",
  "Tremor",
  "Tundra",
  "Twilight",
  "Velvet",
  "Vesper",
  "Whisper",
  "Wisp",
  "Wraith",
  "Zephyr",
]

 end
 
 